using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using cfg;
using Luban;

/// <summary>Checks generated combat tables without launching Unity; this executable is test-only.</summary>
internal static class Program
{
    private static int checks;

    /// <summary>Checks exported movement cylinder dimensions and offsets independently of damage radii.</summary>
    /// <param name="radius">Radius in logical pixels.</param><param name="height">Height in logical pixels.</param>
    /// <param name="x">Ground X offset.</param><param name="y">Ground Y offset.</param><param name="elevation">Cylinder bottom height.</param>
    /// <exception cref="InvalidOperationException">The cylinder is missing or has invalid geometry.</exception>
    private static void ValidateCylinder(float? radius, float? height, float? x, float? y, float? elevation)
    {
        Require(Positive(radius) && Positive(height), "Movement cylinder needs positive radius and height.");
        Require(x.HasValue && y.HasValue && elevation.HasValue && float.IsFinite(x.Value) && float.IsFinite(y.Value) && float.IsFinite(elevation.Value), "Movement cylinder offsets must be finite.");
    }

    /// <summary>Loads the generated bytes, resolves references and runs data and formula checks.</summary>
    /// <param name="args">The sole argument is the generated Luban bytes directory.</param>
    /// <returns>Zero for a complete pass, one for invalid data or a failed check.</returns>
    /// <remarks>Reads configuration files and writes diagnostics; does not edit tables or start the game.</remarks>
    private static int Main(string[] args)
    {
        try
        {
            Require(args.Length == 1, "Pass the Luban bytes directory.");
            var tables = new Tables(name => new ByteBuf(File.ReadAllBytes(Path.Combine(args[0], name + ".bytes"))));
            Validate(tables);
            CheckFormulaFixtures(tables.TbCombatRules.Get(1));
            checks += RuntimeChecks.Run(tables);
            checks += AnimationChecks.Run(tables, args[0]);
            var original = tables.TbAttributeProfile.Get(1).Values;
            var duplicate = new List<AttributeValue>(original);
            duplicate[1] = duplicate[0];
            Reject(() => ValidateProfile(duplicate, tables), "Duplicate attribute was accepted.");
            Reject(() => ValidateProfile(original.Skip(1).ToList(), tables), "Missing attribute was accepted.");
            var oldReference = original[0].AttributeId_Ref;
            try
            {
                original[0].AttributeId_Ref = null;
                Reject(() => ValidateProfile(original, tables), "Unresolved attribute was accepted.");
            }
            finally
            {
                original[0].AttributeId_Ref = oldReference;
            }
            Console.WriteLine($"COMBAT_CONFIG_CHECKS_PASS checks={checks} attributes={tables.TbAttribute.DataList.Count} profiles={tables.TbAttributeProfile.DataList.Count} skills={tables.TbSkillCombat.DataList.Count} combatScenarios={tables.TbPerformanceScenario.DataList.Count(x => x.Kind == EPerformanceKind.Combat)}");
            return 0;
        }
        catch (Exception exception)
        {
            Console.Error.WriteLine(exception);
            return 1;
        }
    }

    /// <summary>Verifies semantic ranges and cross-table contracts after generated reference resolution.</summary>
    /// <param name="tables">Luban Tables loaded from the files being validated.</param>
    /// <exception cref="InvalidOperationException">A required schema, range or reference is invalid.</exception>
    private static void Validate(Tables tables)
    {
        Require(tables.TbAttribute.DataList.Count == 14, "Expected the approved 14 non-element attributes.");
        Require(tables.TbAttribute.DataList.Select(x => x.AttributeType).Distinct().Count() == 14, "Attribute semantic duplicates.");
        foreach (var attribute in tables.TbAttribute.DataList)
        {
            Require(Enum.IsDefined(attribute.AttributeType), $"TbAttribute {attribute.Id}: unknown semantic.");
            Require(Enum.IsDefined(attribute.ValueKind), $"TbAttribute {attribute.Id}: unknown value kind.");
            Require(double.IsFinite(attribute.MinValue) && double.IsFinite(attribute.MaxValue) && attribute.MinValue <= attribute.MaxValue, $"TbAttribute {attribute.Id}: invalid bounds.");
        }
        foreach (var profile in tables.TbAttributeProfile.DataList) ValidateProfile(profile.Values, tables);
        foreach (var actor in tables.TbCharacter.DataList)
        {
            ValidateActor(actor.AttributeProfileId, actor.AttributeProfileId_Ref, actor.DefaultSkillId, actor.DefaultSkillId_Ref, actor.BodyRadius, $"TbCharacter {actor.Id}");
            ValidateCylinder(actor.MoveRadiusPixels, actor.MoveHeightPixels, actor.MoveOffsetXPixels, actor.MoveOffsetYPixels, actor.MoveElevationPixels);
            var tiers = tables.TbHeroWeapon.DataList.Where(w => w.CharacterId == actor.Id).OrderBy(w => w.Tier).ToArray();
            Require(tiers.Length == 5 && tiers.Select(w => w.Tier).SequenceEqual(Enumerable.Range(0, 5)), "Hero requires exactly five distinct weapon tiers.");
            Require(tiers[0].IntegratedInBody && tiers[0].VisualSetId == actor.VisualSetId && tiers.Skip(1).All(w => !w.IntegratedInBody), "Only weapon tier zero is integrated in the body.");
        }
        foreach (var weapon in tables.TbHeroWeapon.DataList)
            Require(weapon.CharacterId_Ref != null && weapon.VisualSetId_Ref != null, "Weapon owner and visual references must resolve.");
        foreach (var actor in tables.TbMonster.DataList)
        {
            ValidateActor(actor.AttributeProfileId, actor.AttributeProfileId_Ref, actor.DefaultSkillId, actor.DefaultSkillId_Ref, actor.BodyRadius, $"TbMonster {actor.Id}");
            ValidateCylinder(actor.MoveRadiusPixels, actor.MoveHeightPixels, actor.MoveOffsetXPixels, actor.MoveOffsetYPixels, actor.MoveElevationPixels);
        }
        foreach (var skill in tables.TbSkill.DataList)
        {
            Require(!skill.CombatProfileId.HasValue || skill.CombatProfileId_Ref != null, $"TbSkill {skill.Id}: missing combat profile.");
            switch (skill.CombatProfileId_Ref?.DeliveryType)
            {
                case ESkillDeliveryType.Projectile:
                    Require(Positive(skill.ProjectileRadius) && skill.ProjectileOffsetX.HasValue && skill.ProjectileOffsetY.HasValue,
                        $"TbSkill {skill.Id}: missing projectile collision.");
                    Require(skill.ProjectileClipId_Ref?.Action == EAnimationAction.Projectile,
                        $"TbSkill {skill.Id}: missing projectile visual.");
                    Require(!skill.ImpactClipId.HasValue || skill.ImpactClipId_Ref?.Action == EAnimationAction.Impact,
                        $"TbSkill {skill.Id}: invalid impact visual.");
                    Require(skill.AreaClipIds.Count == 0 && !skill.AreaRadiusMilli.HasValue,
                        $"TbSkill {skill.Id}: projectile has target-area data.");
                    break;
                case ESkillDeliveryType.TargetArea:
                    Require(!skill.ProjectileRadius.HasValue && !skill.ProjectileOffsetX.HasValue && !skill.ProjectileOffsetY.HasValue,
                        $"TbSkill {skill.Id}: target area has projectile collision.");
                    Require(!skill.ProjectileClipId.HasValue && !skill.ImpactClipId.HasValue,
                        $"TbSkill {skill.Id}: target area has projectile visuals.");
                    Require(skill.AreaRadiusMilli > 0 && skill.AreaClipIds.Count > 0 &&
                        skill.AreaClipIds_Ref.All(x => x?.Action == EAnimationAction.Area),
                        $"TbSkill {skill.Id}: missing target-area radius or visuals.");
                    break;
                default:
                    Require(!skill.ProjectileRadius.HasValue && !skill.ProjectileOffsetX.HasValue && !skill.ProjectileOffsetY.HasValue &&
                        !skill.ProjectileClipId.HasValue && !skill.ImpactClipId.HasValue && skill.AreaClipIds.Count == 0 && !skill.AreaRadiusMilli.HasValue,
                        $"TbSkill {skill.Id}: inactive or melee skill has delivery-specific data.");
                    break;
            }
        }
        foreach (var skill in tables.TbSkillCombat.DataList)
        {
            Require(float.IsFinite(skill.BaseInterval) && skill.BaseInterval > 0 && float.IsFinite(skill.Range) && skill.Range >= 0, $"TbSkillCombat {skill.Id}: invalid interval/range.");
            switch (skill.DeliveryType)
            {
                case ESkillDeliveryType.Projectile:
                    Require(Positive(skill.ProjectileSpeed) && Positive(skill.ProjectileLifetime), $"TbSkillCombat {skill.Id}: missing projectile dimensions.");
                    Require(skill.ProjectileSpeed * skill.ProjectileLifetime >= skill.Range, $"TbSkillCombat {skill.Id}: projectile cannot cover range.");
                    Require(!skill.AttackWindupSeconds.HasValue, $"TbSkillCombat {skill.Id}: projectile has melee windup.");
                    break;
                case ESkillDeliveryType.Melee:
                    Require(skill.AttackWindupSeconds.HasValue && float.IsFinite(skill.AttackWindupSeconds.Value) && skill.AttackWindupSeconds.Value >= 0,
                        $"TbSkillCombat {skill.Id}: missing or invalid attack windup.");
                    Require(!skill.ProjectileSpeed.HasValue && !skill.ProjectileLifetime.HasValue, $"TbSkillCombat {skill.Id}: melee has projectile data.");
                    break;
                case ESkillDeliveryType.TargetArea:
                    Require(!skill.ProjectileSpeed.HasValue && !skill.ProjectileLifetime.HasValue && !skill.AttackWindupSeconds.HasValue,
                        $"TbSkillCombat {skill.Id}: target area has incompatible delivery data.");
                    break;
                default:
                    throw new InvalidOperationException($"TbSkillCombat {skill.Id}: unsupported delivery.");
            }
        }
        var projectileSkillIds = new[] { 20001, 20014, 20032 };
        var targetAreaSkillIds = new[] { 20028, 20043 };
        Require(projectileSkillIds.All(id => tables.TbSkill.Get(id).CombatProfileId_Ref?.DeliveryType == ESkillDeliveryType.Projectile),
            "Approved projectile skill mapping changed.");
        Require(targetAreaSkillIds.All(id => tables.TbSkill.Get(id).CombatProfileId_Ref?.DeliveryType == ESkillDeliveryType.TargetArea),
            "Approved target-area skill mapping changed.");

        var stage = tables.TbStage.Get(1);
        Require(stage.MapId_Ref != null && stage.StageRuleId_Ref != null && stage.CombatRulesId_Ref != null &&
            stage.PresentationId_Ref != null && stage.InitialCharacterId_Ref != null && stage.InitialSkillIds_Ref.All(x => x != null),
            "TbStage 1: run-loop references must resolve.");
        Require(stage.UiSetId == 1 && stage.UiSetId_Ref != null && tables.TbCombatUiSet.DataList.Count == 1,
            "TbStage 1: approved formal UI set must resolve.");
        var ui = stage.UiSetId_Ref;
        Require(new[] { ui.HudPrefabResourceId_Ref, ui.BossBarPrefabResourceId_Ref,
                ui.UpgradePanelPrefabResourceId_Ref, ui.UpgradeCardPrefabResourceId_Ref,
                ui.SettlementPrefabResourceId_Ref }.All(x => x?.Type == EResourceType.Prefab),
            "TbCombatUiSet 1: all formal UI views must reference Prefabs.");
        Require(ui.FontResourceId_Ref?.Type == EResourceType.UnityAsset,
            "TbCombatUiSet 1: font must reference a Unity asset.");
        Require(stage.InitialCharacterId == 10001 && stage.InitialSkillIds.SequenceEqual(new[] { 20001 }),
            "TbStage 1: approved initial loadout changed.");

        var stageRule = stage.StageRuleId_Ref;
        Require(stageRule.DurationMilli == 1080000 && stageRule.BossTimeMilli == stageRule.DurationMilli && stageRule.RandomSeed != 0,
            "TbStageRule 1: duration, boss timing or deterministic seed changed.");
        Require(stageRule.DropProfileId_Ref != null && stageRule.UpgradePoolId_Ref != null && stageRule.BossEncounterId_Ref != null,
            "TbStageRule 1: dependent references must resolve.");
        var phases = stageRule.SpawnPhaseIds_Ref;
        Require(phases.Count == 4 && phases.All(x => x != null) && phases.Select(x => x.Id).Distinct().Count() == phases.Count,
            "TbStageRule 1: four distinct spawn phases are required.");
        Require(phases.Select(x => x.UnitsPerWave).SequenceEqual(new[] { 5, 8, 12, 15 }),
            "TbStageRule 1: approved wave sizes changed.");
        Require(phases[0].BeginTimeMilli == 0 && phases[^1].EndTimeMilli == stageRule.DurationMilli,
            "TbStageRule 1: spawn phases must cover the full pre-boss duration.");
        for (var index = 0; index < phases.Count; index++)
        {
            var phase = phases[index];
            Require(phase.BeginTimeMilli < phase.EndTimeMilli && phase.UnitIntervalMilli > 0 && phase.WaveIntervalMilli > 0,
                $"TbSpawnPhase {phase.Id}: invalid timing.");
            Require(index == 0 || phases[index - 1].EndTimeMilli == phase.BeginTimeMilli,
                $"TbSpawnPhase {phase.Id}: gap or overlap in phase timeline.");
            Require(phase.MonsterWeights.Count > 0 && phase.MonsterWeights.Select(x => x.MonsterId).Distinct().Count() == phase.MonsterWeights.Count &&
                phase.MonsterWeights.All(x => x.MonsterId_Ref != null && x.Weight > 0),
                $"TbSpawnPhase {phase.Id}: invalid monster weights.");
        }

        var normalMonsterIds = phases.SelectMany(x => x.MonsterWeights).Select(x => x.MonsterId).Distinct().OrderBy(x => x).ToArray();
        Require(normalMonsterIds.SequenceEqual(new[] { 10010, 10011, 10012, 10013 }),
            "TbStageRule 1: approved normal-monster roster changed.");
        Require(tables.TbMonster.Get(10011).MovementType == EMovementType.Flying &&
            new[] { 10010, 10012, 10013 }.All(id => tables.TbMonster.Get(id).MovementType == EMovementType.Ground),
            "M1 normal-monster movement types changed.");
        Require(new[] { 10010, 10011, 10012, 10013 }.Select((id, index) =>
                tables.TbMonster.Get(id).AttributeProfileId == index + 5 && tables.TbMonster.Get(id).DefaultSkillId == 20002).All(x => x),
            "M1 normal-monster combat profiles changed.");

        var boss = stageRule.BossEncounterId_Ref;
        Require(boss.MonsterId == 10032 && boss.MonsterId_Ref?.AttributeProfileId == 9 &&
            boss.MonsterId_Ref.DefaultSkillId == 20002 && boss.MonsterId_Ref.MovementType == EMovementType.Ground &&
            boss.SpawnRadiusPixelsMilli > 0 && !string.IsNullOrWhiteSpace(boss.HealthBarText) && boss.VictoryOnDeath,
            "TbBossEncounter 1: approved boss contract changed.");

        var experienceLevels = tables.TbExperienceLevel.DataList
            .Where(x => x.GroupId == stageRule.ExperienceLevelGroupId).OrderBy(x => x.Level).ToArray();
        Require(experienceLevels.Select(x => x.Level).SequenceEqual(Enumerable.Range(2, 19)) &&
            experienceLevels.All(x => x.RequiredExperience > 0) &&
            experienceLevels.Zip(experienceLevels.Skip(1), (left, right) => left.RequiredExperience < right.RequiredExperience).All(x => x),
            "TbExperienceLevel group 1: levels 2-20 require a strictly increasing curve.");

        var drop = stageRule.DropProfileId_Ref;
        Require(drop.ExperienceItemId_Ref != null && drop.ExperienceValue > 0 && drop.MagnetRadiusMilli > 0 &&
            drop.PickupRadiusMilli > 0 && drop.PickupRadiusMilli <= drop.MagnetRadiusMilli && drop.MagnetSpeedMilli > 0,
            "TbDropProfile 1: invalid experience pickup contract.");

        var pool = stageRule.UpgradePoolId_Ref;
        Require(pool.DrawCount == 3 && pool.OptionIds_Ref.Count == 9 && pool.OptionIds_Ref.All(x => x != null) &&
            pool.OptionIds.Distinct().Count() == pool.OptionIds.Count,
            "TbUpgradePool 1: invalid three-choice pool.");
        foreach (var option in pool.OptionIds_Ref)
        {
            Require(Enum.IsDefined(option.Type) && option.MaxRank > 0 && option.Weight > 0 &&
                (!option.IconResourceId.HasValue || option.IconResourceId_Ref != null),
                $"TbUpgradeOption {option.Id}: invalid common fields.");
            Require(option.Modifiers.All(x => x.AttributeId_Ref != null && Enum.IsDefined(x.Operation) && x.ValueMilli != 0),
                $"TbUpgradeOption {option.Id}: invalid attribute modifier.");
            switch (option.Type)
            {
                case EUpgradeOptionType.SkillUnlock:
                    Require(option.TargetSkillId_Ref?.CombatProfileId_Ref != null && option.Modifiers.Count == 0 && !option.HealMilli.HasValue,
                        $"TbUpgradeOption {option.Id}: invalid skill unlock.");
                    break;
                case EUpgradeOptionType.Attribute:
                    Require(!option.TargetSkillId.HasValue && option.Modifiers.Count > 0 && !option.HealMilli.HasValue,
                        $"TbUpgradeOption {option.Id}: invalid attribute upgrade.");
                    break;
                case EUpgradeOptionType.Heal:
                    Require(!option.TargetSkillId.HasValue && option.Modifiers.Count == 0 && option.HealMilli > 0,
                        $"TbUpgradeOption {option.Id}: invalid heal option.");
                    break;
            }
        }
        foreach (var rule in tables.TbCombatRules.DataList)
        {
            Require(rule.DamageRandomMinBp >= 0 && rule.DamageRandomMaxBp >= rule.DamageRandomMinBp, $"TbCombatRules {rule.Id}: random interval.");
            Require(rule.CriticalMultiplierBp >= 10000, $"TbCombatRules {rule.Id}: critical multiplier.");
            Require(rule.ZeroHitDenominatorRateBp >= 0 && rule.ZeroHitDenominatorRateBp <= 10000 && rule.ZeroCritDenominatorRateBp >= 0 && rule.ZeroCritDenominatorRateBp <= 10000, $"TbCombatRules {rule.Id}: zero-denominator rates.");
            Require(Positive(rule.MinAttackInterval) && Positive(rule.TargetRefreshSeconds) && Positive(rule.SpatialCellSize) && Positive(rule.WorldUnitsPerPixel), $"TbCombatRules {rule.Id}: invalid timing/scale.");
            Require(float.IsFinite(rule.PlayerInvulnerabilitySeconds) && rule.PlayerInvulnerabilitySeconds >= 0 && rule.SimulationHz > 0 && rule.MaxCatchUpSteps > 0, $"TbCombatRules {rule.Id}: invalid simulation.");
        }
        foreach (var scenario in tables.TbPerformanceScenario.DataList)
        {
            if (scenario.Kind != EPerformanceKind.Combat)
            {
                Require(!scenario.CombatRulesId.HasValue && !scenario.CharacterId.HasValue && !scenario.PlayerHealthPolicy.HasValue, $"Old scenario {scenario.Id}: combat values leaked.");
                continue;
            }
            Require(scenario.CombatRulesId_Ref != null && scenario.CharacterId_Ref != null && scenario.CharacterProfileOverrideId_Ref != null && scenario.MonsterProfileOverrideId_Ref != null, $"Combat scenario {scenario.Id}: references missing.");
            Require(scenario.CharacterId_Ref.AttributeProfileId_Ref != null && scenario.CharacterId_Ref.DefaultSkillId_Ref?.CombatProfileId_Ref != null, $"Combat scenario {scenario.Id}: player not battle-ready.");
            Require(scenario.MonsterIds_Ref.Count > 0 && scenario.MonsterIds_Ref.All(x => x?.AttributeProfileId_Ref != null && x.DefaultSkillId_Ref?.CombatProfileId_Ref != null), $"Combat scenario {scenario.Id}: monster not battle-ready.");
            Require(Positive(scenario.ArenaHalfWidth) && Positive(scenario.ArenaHalfHeight) && scenario.PlayerStartX.HasValue && scenario.PlayerStartY.HasValue, $"Combat scenario {scenario.Id}: arena missing.");
            Require(float.IsFinite(scenario.PlayerStartX.Value) && float.IsFinite(scenario.PlayerStartY.Value) && Math.Abs(scenario.PlayerStartX.Value) < scenario.ArenaHalfWidth && Math.Abs(scenario.PlayerStartY.Value) < scenario.ArenaHalfHeight, $"Combat scenario {scenario.Id}: player outside arena.");
            Require(scenario.EntityCount > 0 && scenario.ReplenishOnDeath.HasValue && scenario.PlayerHealthPolicy.HasValue && scenario.PlayerInputPolicy.HasValue, $"Combat scenario {scenario.Id}: test policy missing.");
            Require(Enum.IsDefined(scenario.PlayerHealthPolicy.Value) && Enum.IsDefined(scenario.PlayerInputPolicy.Value), $"Combat scenario {scenario.Id}: policy unknown.");
            bool timed = scenario.SpawnRadiusPixels.HasValue || scenario.SpawnIntervalSeconds.HasValue || scenario.SpawnBatchCount.HasValue || scenario.SpawnUnitIntervalSeconds.HasValue;
            if (timed)
            {
                Require(Positive(scenario.SpawnRadiusPixels) && Positive(scenario.SpawnIntervalSeconds) && Positive(scenario.SpawnUnitIntervalSeconds) && scenario.SpawnBatchCount > 0,
                    $"Combat scenario {scenario.Id}: incomplete timed circle spawn.");
                Require(scenario.ReplenishOnDeath == false, $"Combat scenario {scenario.Id}: timed spawn must not replenish on death.");
                Require(float.IsFinite(scenario.SpawnRadiusPixels.Value * scenario.CombatRulesId_Ref.WorldUnitsPerPixel),
                    $"Combat scenario {scenario.Id}: spawn radius conversion overflow.");
            }
            double rows = Math.Ceiling(scenario.EntityCount / (double)scenario.SpawnColumns);
            Require((scenario.SpawnColumns - 1) * scenario.HorizontalSpacing / 2 + scenario.EntityScale / 2 < scenario.ArenaHalfWidth && (rows - 1) * scenario.VerticalSpacing / 2 + scenario.EntityScale / 2 < scenario.ArenaHalfHeight, $"Combat scenario {scenario.Id}: spawn grid outside arena.");
        }
        Require(tables.TbPerformanceScenario.Get(1).EntityCount == 1000, "Old baseline entity count changed.");
        var stress = tables.TbPerformanceScenario.Get(5);
        Require(stress.EntityCount == 1000 && stress.SampleSeconds >= 60 && stress.TargetAverageFps >= 60 && stress.MaxP95FrameTimeMs <= 16.671f, "Stress acceptance target changed.");
        Require(stress.ReplenishOnDeath == true && stress.PlayerHealthPolicy == ETestHealthPolicy.RestoreAfterDamage, "Stress workload cannot be maintained.");
        var values = stress.MonsterProfileOverrideId_Ref.Values.ToDictionary(x => x.AttributeId_Ref.AttributeType, x => x.Value);
        Require(values[EAttributeType.Critical] > 0 && values[EAttributeType.Evasion] > 0, "Stress must exercise criticals and evasion.");
    }

    /// <summary>Checks a complete attribute profile against TbAttribute type and bound definitions.</summary>
    /// <param name="values">Explicit AttributeValue list from TbAttributeProfile.values.</param>
    /// <param name="tables">Resolved tables supplying the required attribute definitions.</param>
    /// <exception cref="InvalidOperationException">A profile has missing, duplicate or illegal values.</exception>
    private static void ValidateProfile(IReadOnlyList<AttributeValue> values, Tables tables)
    {
        Require(values.Count == tables.TbAttribute.DataList.Count, "TbAttributeProfile: incomplete attribute set.");
        Require(values.Select(x => x.AttributeId).Distinct().Count() == values.Count, "TbAttributeProfile: duplicate attribute.");
        foreach (var value in values)
        {
            var definition = value.AttributeId_Ref;
            Require(definition != null, $"TbAttributeProfile: unresolved attribute {value.AttributeId}.");
            Require(double.IsFinite(value.Value) && value.Value >= definition.MinValue && value.Value <= definition.MaxValue, $"TbAttributeProfile: attribute {value.AttributeId} out of range.");
            Require(definition.ValueKind != EAttributeValueKind.Integer || value.Value == Math.Floor(value.Value), $"TbAttributeProfile: attribute {value.AttributeId} must be integer.");
        }
    }

    /// <summary>Checks that a resource-only actor has no partial combat configuration.</summary>
    /// <param name="profileId">Optional attribute profile foreign key.</param>
    /// <param name="profile">Resolved profile.</param>
    /// <param name="skillId">Optional default skill foreign key.</param>
    /// <param name="skill">Resolved default skill.</param>
    /// <param name="radius">Optional physical body radius.</param>
    /// <param name="label">Table and ID used in failure messages.</param>
    /// <exception cref="InvalidOperationException">The actor contains an incomplete combat configuration.</exception>
    private static void ValidateActor(int? profileId, AttributeProfileConfig profile, int? skillId, SkillConfig skill, float? radius, string label)
    {
        bool any = profileId.HasValue || skillId.HasValue || radius.HasValue;
        Require(!any || (profile != null && skill?.CombatProfileId_Ref != null && Positive(radius)), label + ": partial combat configuration.");
    }

    /// <summary>Compares production damage and probability code against independent decimal reference fixtures.</summary>
    /// <param name="rule">TbCombatRules row holding random endpoints, critical multiplier and zero-denominator policy.</param>
    /// <exception cref="InvalidOperationException">A formula fixture or configured reference value does not match.</exception>
    private static void CheckFormulaFixtures(CombatRulesConfig rule)
    {
        Require(rule.DamageRandomMinBp == 8000 && rule.DamageRandomMaxBp == 12000 && rule.CriticalMultiplierBp == 15000, "Reference formula constants changed.");
        var cases = new (decimal a, decimal d, decimal k, decimal r, bool critical, int expected)[]
        {
            (20,0,1,1,false,20),(20,10,1,1,false,13),(20,10,2,1,false,10),(20,100,1,1,false,3),
            (20,0,1,0.8m,false,16),(20,0,1,1.2m,false,24),(20,0,1,1,true,30),(20,10,1,1,true,19),
            (1,10000,1,1,false,0),(0,0,1,1,false,0)
        };
        foreach (var c in cases)
        {
            decimal basis = c.a == 0 ? 0 : Math.Floor(c.a * c.a / (c.a + c.d * c.k) * c.r);
            decimal result = Math.Floor(basis * (c.critical ? rule.CriticalMultiplierBp / 10000m : 1));
            Require(result == c.expected, $"Formula fixture a={c.a}, d={c.d}.");
            Require(Roguelike.Features.Combat.CombatMath.Damage((double)c.a, (double)c.d, (double)c.k,
                (int)(c.r * 10000), rule.CriticalMultiplierBp, c.critical) == c.expected, "Runtime damage fixture.");
        }
        Require(ProbabilityThreshold(100,25,rule.ZeroHitDenominatorRateBp) == 8000, "Hit threshold.");
        Require(ProbabilityThreshold(25,100,rule.ZeroCritDenominatorRateBp) == 2000, "Critical threshold.");
        Require(ProbabilityThreshold(200,100,rule.ZeroHitDenominatorRateBp) == 6666, "Threshold truncation.");
        Require(ProbabilityThreshold(0,0,rule.ZeroHitDenominatorRateBp) == 10000, "Zero hit denominator.");
        Require(ProbabilityThreshold(0,0,rule.ZeroCritDenominatorRateBp) == 0, "Zero critical denominator.");
        foreach (var pair in new[] { (100,25), (25,100), (200,100), (0,0), (0,100), (100,0) })
            Require(Roguelike.Features.Combat.CombatMath.ProbabilityThreshold(pair.Item1, pair.Item2, rule.ZeroHitDenominatorRateBp)
                == ProbabilityThreshold(pair.Item1, pair.Item2, rule.ZeroHitDenominatorRateBp), "Runtime probability oracle.");
    }

    /// <summary>Computes an exact decimal probability threshold for test fixtures.</summary>
    /// <param name="attacker">Weighted attacker attribute.</param>
    /// <param name="defender">Weighted defender attribute.</param>
    /// <param name="zeroPolicy">Table-configured threshold when both values are zero.</param>
    /// <returns>The truncated basis-point threshold.</returns>
    private static int ProbabilityThreshold(decimal attacker, decimal defender, int zeroPolicy)
    {
        return attacker + defender == 0 ? zeroPolicy : (int)Math.Floor(attacker / (attacker + defender) * 10000);
    }

    /// <summary>Tests whether an optional configuration scalar is present, finite and positive.</summary>
    /// <param name="value">Scalar under validation.</param>
    /// <returns>True only for finite positive values.</returns>
    private static bool Positive(float? value) => value.HasValue && float.IsFinite(value.Value) && value.Value > 0;

    /// <summary>Ensures a deliberate malformed-input test reaches a validation failure.</summary>
    /// <param name="action">Validation action on test-owned data.</param>
    /// <param name="message">Failure explanation if invalid input is accepted.</param>
    /// <exception cref="InvalidOperationException">The validation action incorrectly accepts malformed data.</exception>
    private static void Reject(Action action, string message)
    {
        try { action(); }
        catch (InvalidOperationException) { checks++; return; }
        throw new InvalidOperationException(message);
    }

    /// <summary>Counts a check and throws a diagnostic failure when its predicate is false.</summary>
    /// <param name="condition">Required invariant.</param>
    /// <param name="message">Failure description including table context.</param>
    /// <exception cref="InvalidOperationException">The invariant is false.</exception>
    private static void Require(bool condition, string message)
    {
        if (!condition) throw new InvalidOperationException(message);
        checks++;
    }
}
